name: Dristi-kerala Image Build workflow
on:
  push:
    branches:
      - scheduler
  workflow_dispatch:

jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io

      - name: Build and Push Docker image for Scheduler-svc
        run: |
          docker build --build-arg WORK_DIR="backend/scheduler-svc" -t pucarsolutionsdev.azurecr.io/scheduler-svc:v1.0.0-${{ github.sha }} -f build/maven/Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/scheduler-svc:v1.0.0-${{ github.sha }}

      - name: Build and Push Docker image for scheduler-svc_DB
        run: |
          docker build  -t pucarsolutionsdev.azurecr.io/scheduler-svc_db:v1.0.0-${{ github.sha }} -f  Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/scheduler-svc_db:v1.0.0-${{ github.sha }}
        working-directory: backend/scheduler-svc/src/main/resources/db
