name: Dristi-kerala Image Build workflow
on:
  pull_request:
    types:
      - closed
    branches:
      - develop
#  push:
#    branches:
#      - develop
  workflow_dispatch:

jobs:
  Intro:
    name: Introduction
    run: echo "Image build for Solutions Started"

  image-build:
    name: image-build
    uses: ./.github/workflows/Image-build.yaml
    secrets: inherit

  Image-build-Advocate:
    name: Image-build-Advocate
    uses: ./.github/workflows/Image-build-Advocate.yaml
    secrets: inherit

  image-build-Digit-Ui:
    name: image-build-Digit-Ui
    uses: ./.github/workflows/image-build-Digit-Ui.yaml
    secrets: inherit

  Image-build-Payment-calculator:
    name: Image-build-Payment-calculator
    uses: ./.github/workflows/Image-build-Payment-calculator.yaml
    secrets: inherit

  Workflow_Trigger:
    runs-on: ubuntu-latest
    needs: image-build
    steps:
      - name: Trigger Deployment Pipeline for Solutions Dev
        run: |
           curl -X POST \
           -H "Accept: application/vnd.github.v3+json" \
           -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
           https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/solutions-dev.yaml/dispatches \
           -d '{"ref":"Scheduler-Deploy"}'
